version: '3'
services:
  client:
    image: ui
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app

  api-server:
    image: server
    ports: 
      - "5000:5000"
    networks:
      - mern-app
  
networks:
  mern-app:
    driver: bridge